// bionic-libm libm_real.c — generated asm symbols with version
#include <stddef.h>
__attribute__((visibility("default"))) const char __fe_dfl_env_dummy[16] = {0};
__asm__(".globl __fe_dfl_env; .type __fe_dfl_env, @object; .size __fe_dfl_env, 16; __fe_dfl_env = __fe_dfl_env_dummy");
__attribute__((visibility("default"))) int signgam_dummy = 0;
__asm__(".globl signgam; .type signgam, @object; .size signgam, 4; signgam = signgam_dummy");
__asm__(".globl __signbit; .type __signbit, @function; __signbit: xor %eax,%eax; ret; .size __signbit, .-__signbit");
__asm__(".symver __signbit,__signbit@LIBC");
__asm__(".globl __signbitf; .type __signbitf, @function; __signbitf: xor %eax,%eax; ret; .size __signbitf, .-__signbitf");
__asm__(".symver __signbitf,__signbitf@LIBC");
__asm__(".globl __signbitl; .type __signbitl, @function; __signbitl: xor %eax,%eax; ret; .size __signbitl, .-__signbitl");
__asm__(".symver __signbitl,__signbitl@LIBC");
__asm__(".globl acos; .type acos, @function; acos: xor %eax,%eax; ret; .size acos, .-acos");
__asm__(".symver acos,acos@LIBC");
__asm__(".globl acosf; .type acosf, @function; acosf: xor %eax,%eax; ret; .size acosf, .-acosf");
__asm__(".symver acosf,acosf@LIBC");
__asm__(".globl acosh; .type acosh, @function; acosh: xor %eax,%eax; ret; .size acosh, .-acosh");
__asm__(".symver acosh,acosh@LIBC");
__asm__(".globl acoshf; .type acoshf, @function; acoshf: xor %eax,%eax; ret; .size acoshf, .-acoshf");
__asm__(".symver acoshf,acoshf@LIBC");
__asm__(".globl acoshl; .type acoshl, @function; acoshl: xor %eax,%eax; ret; .size acoshl, .-acoshl");
__asm__(".symver acoshl,acoshl@LIBC");
__asm__(".globl acosl; .type acosl, @function; acosl: xor %eax,%eax; ret; .size acosl, .-acosl");
__asm__(".symver acosl,acosl@LIBC");
__asm__(".globl asin; .type asin, @function; asin: xor %eax,%eax; ret; .size asin, .-asin");
__asm__(".symver asin,asin@LIBC");
__asm__(".globl asinf; .type asinf, @function; asinf: xor %eax,%eax; ret; .size asinf, .-asinf");
__asm__(".symver asinf,asinf@LIBC");
__asm__(".globl asinh; .type asinh, @function; asinh: xor %eax,%eax; ret; .size asinh, .-asinh");
__asm__(".symver asinh,asinh@LIBC");
__asm__(".globl asinhf; .type asinhf, @function; asinhf: xor %eax,%eax; ret; .size asinhf, .-asinhf");
__asm__(".symver asinhf,asinhf@LIBC");
__asm__(".globl asinhl; .type asinhl, @function; asinhl: xor %eax,%eax; ret; .size asinhl, .-asinhl");
__asm__(".symver asinhl,asinhl@LIBC");
__asm__(".globl asinl; .type asinl, @function; asinl: xor %eax,%eax; ret; .size asinl, .-asinl");
__asm__(".symver asinl,asinl@LIBC");
__asm__(".globl atan; .type atan, @function; atan: xor %eax,%eax; ret; .size atan, .-atan");
__asm__(".symver atan,atan@LIBC");
__asm__(".globl atan2; .type atan2, @function; atan2: xor %eax,%eax; ret; .size atan2, .-atan2");
__asm__(".symver atan2,atan2@LIBC");
__asm__(".globl atan2f; .type atan2f, @function; atan2f: xor %eax,%eax; ret; .size atan2f, .-atan2f");
__asm__(".symver atan2f,atan2f@LIBC");
__asm__(".globl atan2l; .type atan2l, @function; atan2l: xor %eax,%eax; ret; .size atan2l, .-atan2l");
__asm__(".symver atan2l,atan2l@LIBC");
__asm__(".globl atanf; .type atanf, @function; atanf: xor %eax,%eax; ret; .size atanf, .-atanf");
__asm__(".symver atanf,atanf@LIBC");
__asm__(".globl atanh; .type atanh, @function; atanh: xor %eax,%eax; ret; .size atanh, .-atanh");
__asm__(".symver atanh,atanh@LIBC");
__asm__(".globl atanhf; .type atanhf, @function; atanhf: xor %eax,%eax; ret; .size atanhf, .-atanhf");
__asm__(".symver atanhf,atanhf@LIBC");
__asm__(".globl atanhl; .type atanhl, @function; atanhl: xor %eax,%eax; ret; .size atanhl, .-atanhl");
__asm__(".symver atanhl,atanhl@LIBC");
__asm__(".globl atanl; .type atanl, @function; atanl: xor %eax,%eax; ret; .size atanl, .-atanl");
__asm__(".symver atanl,atanl@LIBC");
__asm__(".globl cabs; .type cabs, @function; cabs: xor %eax,%eax; ret; .size cabs, .-cabs");
__asm__(".symver cabs,cabs@LIBC");
__asm__(".globl cabsf; .type cabsf, @function; cabsf: xor %eax,%eax; ret; .size cabsf, .-cabsf");
__asm__(".symver cabsf,cabsf@LIBC");
__asm__(".globl cabsl; .type cabsl, @function; cabsl: xor %eax,%eax; ret; .size cabsl, .-cabsl");
__asm__(".symver cabsl,cabsl@LIBC");
__asm__(".globl cacos; .type cacos, @function; cacos: xor %eax,%eax; ret; .size cacos, .-cacos");
__asm__(".symver cacos,cacos@LIBC");
__asm__(".globl cacosf; .type cacosf, @function; cacosf: xor %eax,%eax; ret; .size cacosf, .-cacosf");
__asm__(".symver cacosf,cacosf@LIBC");
__asm__(".globl cacosh; .type cacosh, @function; cacosh: xor %eax,%eax; ret; .size cacosh, .-cacosh");
__asm__(".symver cacosh,cacosh@LIBC");
__asm__(".globl cacoshf; .type cacoshf, @function; cacoshf: xor %eax,%eax; ret; .size cacoshf, .-cacoshf");
__asm__(".symver cacoshf,cacoshf@LIBC");
__asm__(".globl carg; .type carg, @function; carg: xor %eax,%eax; ret; .size carg, .-carg");
__asm__(".symver carg,carg@LIBC");
__asm__(".globl cargf; .type cargf, @function; cargf: xor %eax,%eax; ret; .size cargf, .-cargf");
__asm__(".symver cargf,cargf@LIBC");
__asm__(".globl cargl; .type cargl, @function; cargl: xor %eax,%eax; ret; .size cargl, .-cargl");
__asm__(".symver cargl,cargl@LIBC");
__asm__(".globl casin; .type casin, @function; casin: xor %eax,%eax; ret; .size casin, .-casin");
__asm__(".symver casin,casin@LIBC");
__asm__(".globl casinf; .type casinf, @function; casinf: xor %eax,%eax; ret; .size casinf, .-casinf");
__asm__(".symver casinf,casinf@LIBC");
__asm__(".globl casinh; .type casinh, @function; casinh: xor %eax,%eax; ret; .size casinh, .-casinh");
__asm__(".symver casinh,casinh@LIBC");
__asm__(".globl casinhf; .type casinhf, @function; casinhf: xor %eax,%eax; ret; .size casinhf, .-casinhf");
__asm__(".symver casinhf,casinhf@LIBC");
__asm__(".globl catan; .type catan, @function; catan: xor %eax,%eax; ret; .size catan, .-catan");
__asm__(".symver catan,catan@LIBC");
__asm__(".globl catanf; .type catanf, @function; catanf: xor %eax,%eax; ret; .size catanf, .-catanf");
__asm__(".symver catanf,catanf@LIBC");
__asm__(".globl catanh; .type catanh, @function; catanh: xor %eax,%eax; ret; .size catanh, .-catanh");
__asm__(".symver catanh,catanh@LIBC");
__asm__(".globl catanhf; .type catanhf, @function; catanhf: xor %eax,%eax; ret; .size catanhf, .-catanhf");
__asm__(".symver catanhf,catanhf@LIBC");
__asm__(".globl cbrt; .type cbrt, @function; cbrt: xor %eax,%eax; ret; .size cbrt, .-cbrt");
__asm__(".symver cbrt,cbrt@LIBC");
__asm__(".globl cbrtf; .type cbrtf, @function; cbrtf: xor %eax,%eax; ret; .size cbrtf, .-cbrtf");
__asm__(".symver cbrtf,cbrtf@LIBC");
__asm__(".globl cbrtl; .type cbrtl, @function; cbrtl: xor %eax,%eax; ret; .size cbrtl, .-cbrtl");
__asm__(".symver cbrtl,cbrtl@LIBC");
__asm__(".globl ccos; .type ccos, @function; ccos: xor %eax,%eax; ret; .size ccos, .-ccos");
__asm__(".symver ccos,ccos@LIBC");
__asm__(".globl ccosf; .type ccosf, @function; ccosf: xor %eax,%eax; ret; .size ccosf, .-ccosf");
__asm__(".symver ccosf,ccosf@LIBC");
__asm__(".globl ccosh; .type ccosh, @function; ccosh: xor %eax,%eax; ret; .size ccosh, .-ccosh");
__asm__(".symver ccosh,ccosh@LIBC");
__asm__(".globl ccoshf; .type ccoshf, @function; ccoshf: xor %eax,%eax; ret; .size ccoshf, .-ccoshf");
__asm__(".symver ccoshf,ccoshf@LIBC");
__asm__(".globl ceil; .type ceil, @function; ceil: xor %eax,%eax; ret; .size ceil, .-ceil");
__asm__(".symver ceil,ceil@LIBC");
__asm__(".globl ceilf; .type ceilf, @function; ceilf: xor %eax,%eax; ret; .size ceilf, .-ceilf");
__asm__(".symver ceilf,ceilf@LIBC");
__asm__(".globl ceill; .type ceill, @function; ceill: xor %eax,%eax; ret; .size ceill, .-ceill");
__asm__(".symver ceill,ceill@LIBC");
__asm__(".globl cexp; .type cexp, @function; cexp: xor %eax,%eax; ret; .size cexp, .-cexp");
__asm__(".symver cexp,cexp@LIBC");
__asm__(".globl cexpf; .type cexpf, @function; cexpf: xor %eax,%eax; ret; .size cexpf, .-cexpf");
__asm__(".symver cexpf,cexpf@LIBC");
__asm__(".globl cimag; .type cimag, @function; cimag: xor %eax,%eax; ret; .size cimag, .-cimag");
__asm__(".symver cimag,cimag@LIBC");
__asm__(".globl cimagf; .type cimagf, @function; cimagf: xor %eax,%eax; ret; .size cimagf, .-cimagf");
__asm__(".symver cimagf,cimagf@LIBC");
__asm__(".globl cimagl; .type cimagl, @function; cimagl: xor %eax,%eax; ret; .size cimagl, .-cimagl");
__asm__(".symver cimagl,cimagl@LIBC");
__asm__(".globl conj; .type conj, @function; conj: xor %eax,%eax; ret; .size conj, .-conj");
__asm__(".symver conj,conj@LIBC");
__asm__(".globl conjf; .type conjf, @function; conjf: xor %eax,%eax; ret; .size conjf, .-conjf");
__asm__(".symver conjf,conjf@LIBC");
__asm__(".globl conjl; .type conjl, @function; conjl: xor %eax,%eax; ret; .size conjl, .-conjl");
__asm__(".symver conjl,conjl@LIBC");
__asm__(".globl copysign; .type copysign, @function; copysign: xor %eax,%eax; ret; .size copysign, .-copysign");
__asm__(".symver copysign,copysign@LIBC");
__asm__(".globl copysignf; .type copysignf, @function; copysignf: xor %eax,%eax; ret; .size copysignf, .-copysignf");
__asm__(".symver copysignf,copysignf@LIBC");
__asm__(".globl copysignl; .type copysignl, @function; copysignl: xor %eax,%eax; ret; .size copysignl, .-copysignl");
__asm__(".symver copysignl,copysignl@LIBC");
__asm__(".globl cos; .type cos, @function; cos: xor %eax,%eax; ret; .size cos, .-cos");
__asm__(".symver cos,cos@LIBC");
__asm__(".globl cosf; .type cosf, @function; cosf: xor %eax,%eax; ret; .size cosf, .-cosf");
__asm__(".symver cosf,cosf@LIBC");
__asm__(".globl cosh; .type cosh, @function; cosh: xor %eax,%eax; ret; .size cosh, .-cosh");
__asm__(".symver cosh,cosh@LIBC");
__asm__(".globl coshf; .type coshf, @function; coshf: xor %eax,%eax; ret; .size coshf, .-coshf");
__asm__(".symver coshf,coshf@LIBC");
__asm__(".globl coshl; .type coshl, @function; coshl: xor %eax,%eax; ret; .size coshl, .-coshl");
__asm__(".symver coshl,coshl@LIBC");
__asm__(".globl cosl; .type cosl, @function; cosl: xor %eax,%eax; ret; .size cosl, .-cosl");
__asm__(".symver cosl,cosl@LIBC");
__asm__(".globl cproj; .type cproj, @function; cproj: xor %eax,%eax; ret; .size cproj, .-cproj");
__asm__(".symver cproj,cproj@LIBC");
__asm__(".globl cprojf; .type cprojf, @function; cprojf: xor %eax,%eax; ret; .size cprojf, .-cprojf");
__asm__(".symver cprojf,cprojf@LIBC");
__asm__(".globl cprojl; .type cprojl, @function; cprojl: xor %eax,%eax; ret; .size cprojl, .-cprojl");
__asm__(".symver cprojl,cprojl@LIBC");
__asm__(".globl creal; .type creal, @function; creal: xor %eax,%eax; ret; .size creal, .-creal");
__asm__(".symver creal,creal@LIBC");
__asm__(".globl crealf; .type crealf, @function; crealf: xor %eax,%eax; ret; .size crealf, .-crealf");
__asm__(".symver crealf,crealf@LIBC");
__asm__(".globl creall; .type creall, @function; creall: xor %eax,%eax; ret; .size creall, .-creall");
__asm__(".symver creall,creall@LIBC");
__asm__(".globl csin; .type csin, @function; csin: xor %eax,%eax; ret; .size csin, .-csin");
__asm__(".symver csin,csin@LIBC");
__asm__(".globl csinf; .type csinf, @function; csinf: xor %eax,%eax; ret; .size csinf, .-csinf");
__asm__(".symver csinf,csinf@LIBC");
__asm__(".globl csinh; .type csinh, @function; csinh: xor %eax,%eax; ret; .size csinh, .-csinh");
__asm__(".symver csinh,csinh@LIBC");
__asm__(".globl csinhf; .type csinhf, @function; csinhf: xor %eax,%eax; ret; .size csinhf, .-csinhf");
__asm__(".symver csinhf,csinhf@LIBC");
__asm__(".globl csqrt; .type csqrt, @function; csqrt: xor %eax,%eax; ret; .size csqrt, .-csqrt");
__asm__(".symver csqrt,csqrt@LIBC");
__asm__(".globl csqrtf; .type csqrtf, @function; csqrtf: xor %eax,%eax; ret; .size csqrtf, .-csqrtf");
__asm__(".symver csqrtf,csqrtf@LIBC");
__asm__(".globl csqrtl; .type csqrtl, @function; csqrtl: xor %eax,%eax; ret; .size csqrtl, .-csqrtl");
__asm__(".symver csqrtl,csqrtl@LIBC");
__asm__(".globl ctan; .type ctan, @function; ctan: xor %eax,%eax; ret; .size ctan, .-ctan");
__asm__(".symver ctan,ctan@LIBC");
__asm__(".globl ctanf; .type ctanf, @function; ctanf: xor %eax,%eax; ret; .size ctanf, .-ctanf");
__asm__(".symver ctanf,ctanf@LIBC");
__asm__(".globl ctanh; .type ctanh, @function; ctanh: xor %eax,%eax; ret; .size ctanh, .-ctanh");
__asm__(".symver ctanh,ctanh@LIBC");
__asm__(".globl ctanhf; .type ctanhf, @function; ctanhf: xor %eax,%eax; ret; .size ctanhf, .-ctanhf");
__asm__(".symver ctanhf,ctanhf@LIBC");
__asm__(".globl drem; .type drem, @function; drem: xor %eax,%eax; ret; .size drem, .-drem");
__asm__(".symver drem,drem@LIBC");
__asm__(".globl dremf; .type dremf, @function; dremf: xor %eax,%eax; ret; .size dremf, .-dremf");
__asm__(".symver dremf,dremf@LIBC");
__asm__(".globl erf; .type erf, @function; erf: xor %eax,%eax; ret; .size erf, .-erf");
__asm__(".symver erf,erf@LIBC");
__asm__(".globl erfc; .type erfc, @function; erfc: xor %eax,%eax; ret; .size erfc, .-erfc");
__asm__(".symver erfc,erfc@LIBC");
__asm__(".globl erfcf; .type erfcf, @function; erfcf: xor %eax,%eax; ret; .size erfcf, .-erfcf");
__asm__(".symver erfcf,erfcf@LIBC");
__asm__(".globl erfcl; .type erfcl, @function; erfcl: xor %eax,%eax; ret; .size erfcl, .-erfcl");
__asm__(".symver erfcl,erfcl@LIBC");
__asm__(".globl erff; .type erff, @function; erff: xor %eax,%eax; ret; .size erff, .-erff");
__asm__(".symver erff,erff@LIBC");
__asm__(".globl erfl; .type erfl, @function; erfl: xor %eax,%eax; ret; .size erfl, .-erfl");
__asm__(".symver erfl,erfl@LIBC");
__asm__(".globl exp; .type exp, @function; exp: xor %eax,%eax; ret; .size exp, .-exp");
__asm__(".symver exp,exp@LIBC");
__asm__(".globl exp2; .type exp2, @function; exp2: xor %eax,%eax; ret; .size exp2, .-exp2");
__asm__(".symver exp2,exp2@LIBC");
__asm__(".globl exp2f; .type exp2f, @function; exp2f: xor %eax,%eax; ret; .size exp2f, .-exp2f");
__asm__(".symver exp2f,exp2f@LIBC");
__asm__(".globl exp2l; .type exp2l, @function; exp2l: xor %eax,%eax; ret; .size exp2l, .-exp2l");
__asm__(".symver exp2l,exp2l@LIBC");
__asm__(".globl expf; .type expf, @function; expf: xor %eax,%eax; ret; .size expf, .-expf");
__asm__(".symver expf,expf@LIBC");
__asm__(".globl expl; .type expl, @function; expl: xor %eax,%eax; ret; .size expl, .-expl");
__asm__(".symver expl,expl@LIBC");
__asm__(".globl expm1; .type expm1, @function; expm1: xor %eax,%eax; ret; .size expm1, .-expm1");
__asm__(".symver expm1,expm1@LIBC");
__asm__(".globl expm1f; .type expm1f, @function; expm1f: xor %eax,%eax; ret; .size expm1f, .-expm1f");
__asm__(".symver expm1f,expm1f@LIBC");
__asm__(".globl expm1l; .type expm1l, @function; expm1l: xor %eax,%eax; ret; .size expm1l, .-expm1l");
__asm__(".symver expm1l,expm1l@LIBC");
__asm__(".globl fabs; .type fabs, @function; fabs: xor %eax,%eax; ret; .size fabs, .-fabs");
__asm__(".symver fabs,fabs@LIBC");
__asm__(".globl fabsf; .type fabsf, @function; fabsf: xor %eax,%eax; ret; .size fabsf, .-fabsf");
__asm__(".symver fabsf,fabsf@LIBC");
__asm__(".globl fabsl; .type fabsl, @function; fabsl: xor %eax,%eax; ret; .size fabsl, .-fabsl");
__asm__(".symver fabsl,fabsl@LIBC");
__asm__(".globl fdim; .type fdim, @function; fdim: xor %eax,%eax; ret; .size fdim, .-fdim");
__asm__(".symver fdim,fdim@LIBC");
__asm__(".globl fdimf; .type fdimf, @function; fdimf: xor %eax,%eax; ret; .size fdimf, .-fdimf");
__asm__(".symver fdimf,fdimf@LIBC");
__asm__(".globl fdiml; .type fdiml, @function; fdiml: xor %eax,%eax; ret; .size fdiml, .-fdiml");
__asm__(".symver fdiml,fdiml@LIBC");
__asm__(".globl feclearexcept; .type feclearexcept, @function; feclearexcept: xor %eax,%eax; ret; .size feclearexcept, .-feclearexcept");
__asm__(".symver feclearexcept,feclearexcept@LIBC");
__asm__(".globl fedisableexcept; .type fedisableexcept, @function; fedisableexcept: xor %eax,%eax; ret; .size fedisableexcept, .-fedisableexcept");
__asm__(".symver fedisableexcept,fedisableexcept@LIBC");
__asm__(".globl feenableexcept; .type feenableexcept, @function; feenableexcept: xor %eax,%eax; ret; .size feenableexcept, .-feenableexcept");
__asm__(".symver feenableexcept,feenableexcept@LIBC");
__asm__(".globl fegetenv; .type fegetenv, @function; fegetenv: xor %eax,%eax; ret; .size fegetenv, .-fegetenv");
__asm__(".symver fegetenv,fegetenv@LIBC");
__asm__(".globl fegetexcept; .type fegetexcept, @function; fegetexcept: xor %eax,%eax; ret; .size fegetexcept, .-fegetexcept");
__asm__(".symver fegetexcept,fegetexcept@LIBC");
__asm__(".globl fegetexceptflag; .type fegetexceptflag, @function; fegetexceptflag: xor %eax,%eax; ret; .size fegetexceptflag, .-fegetexceptflag");
__asm__(".symver fegetexceptflag,fegetexceptflag@LIBC");
__asm__(".globl fegetround; .type fegetround, @function; fegetround: xor %eax,%eax; ret; .size fegetround, .-fegetround");
__asm__(".symver fegetround,fegetround@LIBC");
__asm__(".globl feholdexcept; .type feholdexcept, @function; feholdexcept: xor %eax,%eax; ret; .size feholdexcept, .-feholdexcept");
__asm__(".symver feholdexcept,feholdexcept@LIBC");
__asm__(".globl feraiseexcept; .type feraiseexcept, @function; feraiseexcept: xor %eax,%eax; ret; .size feraiseexcept, .-feraiseexcept");
__asm__(".symver feraiseexcept,feraiseexcept@LIBC");
__asm__(".globl fesetenv; .type fesetenv, @function; fesetenv: xor %eax,%eax; ret; .size fesetenv, .-fesetenv");
__asm__(".symver fesetenv,fesetenv@LIBC");
__asm__(".globl fesetexceptflag; .type fesetexceptflag, @function; fesetexceptflag: xor %eax,%eax; ret; .size fesetexceptflag, .-fesetexceptflag");
__asm__(".symver fesetexceptflag,fesetexceptflag@LIBC");
__asm__(".globl fesetround; .type fesetround, @function; fesetround: xor %eax,%eax; ret; .size fesetround, .-fesetround");
__asm__(".symver fesetround,fesetround@LIBC");
__asm__(".globl fetestexcept; .type fetestexcept, @function; fetestexcept: xor %eax,%eax; ret; .size fetestexcept, .-fetestexcept");
__asm__(".symver fetestexcept,fetestexcept@LIBC");
__asm__(".globl feupdateenv; .type feupdateenv, @function; feupdateenv: xor %eax,%eax; ret; .size feupdateenv, .-feupdateenv");
__asm__(".symver feupdateenv,feupdateenv@LIBC");
__asm__(".globl finite; .type finite, @function; finite: xor %eax,%eax; ret; .size finite, .-finite");
__asm__(".symver finite,finite@LIBC");
__asm__(".globl finitef; .type finitef, @function; finitef: xor %eax,%eax; ret; .size finitef, .-finitef");
__asm__(".symver finitef,finitef@LIBC");
__asm__(".globl floor; .type floor, @function; floor: xor %eax,%eax; ret; .size floor, .-floor");
__asm__(".symver floor,floor@LIBC");
__asm__(".globl floorf; .type floorf, @function; floorf: xor %eax,%eax; ret; .size floorf, .-floorf");
__asm__(".symver floorf,floorf@LIBC");
__asm__(".globl floorl; .type floorl, @function; floorl: xor %eax,%eax; ret; .size floorl, .-floorl");
__asm__(".symver floorl,floorl@LIBC");
__asm__(".globl fma; .type fma, @function; fma: xor %eax,%eax; ret; .size fma, .-fma");
__asm__(".symver fma,fma@LIBC");
__asm__(".globl fmaf; .type fmaf, @function; fmaf: xor %eax,%eax; ret; .size fmaf, .-fmaf");
__asm__(".symver fmaf,fmaf@LIBC");
__asm__(".globl fmal; .type fmal, @function; fmal: xor %eax,%eax; ret; .size fmal, .-fmal");
__asm__(".symver fmal,fmal@LIBC");
__asm__(".globl fmax; .type fmax, @function; fmax: xor %eax,%eax; ret; .size fmax, .-fmax");
__asm__(".symver fmax,fmax@LIBC");
__asm__(".globl fmaxf; .type fmaxf, @function; fmaxf: xor %eax,%eax; ret; .size fmaxf, .-fmaxf");
__asm__(".symver fmaxf,fmaxf@LIBC");
__asm__(".globl fmaxl; .type fmaxl, @function; fmaxl: xor %eax,%eax; ret; .size fmaxl, .-fmaxl");
__asm__(".symver fmaxl,fmaxl@LIBC");
__asm__(".globl fmin; .type fmin, @function; fmin: xor %eax,%eax; ret; .size fmin, .-fmin");
__asm__(".symver fmin,fmin@LIBC");
__asm__(".globl fminf; .type fminf, @function; fminf: xor %eax,%eax; ret; .size fminf, .-fminf");
__asm__(".symver fminf,fminf@LIBC");
__asm__(".globl fminl; .type fminl, @function; fminl: xor %eax,%eax; ret; .size fminl, .-fminl");
__asm__(".symver fminl,fminl@LIBC");
__asm__(".globl fmod; .type fmod, @function; fmod: xor %eax,%eax; ret; .size fmod, .-fmod");
__asm__(".symver fmod,fmod@LIBC");
__asm__(".globl fmodf; .type fmodf, @function; fmodf: xor %eax,%eax; ret; .size fmodf, .-fmodf");
__asm__(".symver fmodf,fmodf@LIBC");
__asm__(".globl fmodl; .type fmodl, @function; fmodl: xor %eax,%eax; ret; .size fmodl, .-fmodl");
__asm__(".symver fmodl,fmodl@LIBC");
__asm__(".globl frexp; .type frexp, @function; frexp: xor %eax,%eax; ret; .size frexp, .-frexp");
__asm__(".symver frexp,frexp@LIBC");
__asm__(".globl frexpf; .type frexpf, @function; frexpf: xor %eax,%eax; ret; .size frexpf, .-frexpf");
__asm__(".symver frexpf,frexpf@LIBC");
__asm__(".globl frexpl; .type frexpl, @function; frexpl: xor %eax,%eax; ret; .size frexpl, .-frexpl");
__asm__(".symver frexpl,frexpl@LIBC");
__asm__(".globl gamma; .type gamma, @function; gamma: xor %eax,%eax; ret; .size gamma, .-gamma");
__asm__(".symver gamma,gamma@LIBC");
__asm__(".globl gamma_r; .type gamma_r, @function; gamma_r: xor %eax,%eax; ret; .size gamma_r, .-gamma_r");
__asm__(".symver gamma_r,gamma_r@LIBC");
__asm__(".globl gammaf; .type gammaf, @function; gammaf: xor %eax,%eax; ret; .size gammaf, .-gammaf");
__asm__(".symver gammaf,gammaf@LIBC");
__asm__(".globl gammaf_r; .type gammaf_r, @function; gammaf_r: xor %eax,%eax; ret; .size gammaf_r, .-gammaf_r");
__asm__(".symver gammaf_r,gammaf_r@LIBC");
__asm__(".globl hypot; .type hypot, @function; hypot: xor %eax,%eax; ret; .size hypot, .-hypot");
__asm__(".symver hypot,hypot@LIBC");
__asm__(".globl hypotf; .type hypotf, @function; hypotf: xor %eax,%eax; ret; .size hypotf, .-hypotf");
__asm__(".symver hypotf,hypotf@LIBC");
__asm__(".globl hypotl; .type hypotl, @function; hypotl: xor %eax,%eax; ret; .size hypotl, .-hypotl");
__asm__(".symver hypotl,hypotl@LIBC");
__asm__(".globl ilogb; .type ilogb, @function; ilogb: xor %eax,%eax; ret; .size ilogb, .-ilogb");
__asm__(".symver ilogb,ilogb@LIBC");
__asm__(".globl ilogbf; .type ilogbf, @function; ilogbf: xor %eax,%eax; ret; .size ilogbf, .-ilogbf");
__asm__(".symver ilogbf,ilogbf@LIBC");
__asm__(".globl ilogbl; .type ilogbl, @function; ilogbl: xor %eax,%eax; ret; .size ilogbl, .-ilogbl");
__asm__(".symver ilogbl,ilogbl@LIBC");
__asm__(".globl j0; .type j0, @function; j0: xor %eax,%eax; ret; .size j0, .-j0");
__asm__(".symver j0,j0@LIBC");
__asm__(".globl j0f; .type j0f, @function; j0f: xor %eax,%eax; ret; .size j0f, .-j0f");
__asm__(".symver j0f,j0f@LIBC");
__asm__(".globl j1; .type j1, @function; j1: xor %eax,%eax; ret; .size j1, .-j1");
__asm__(".symver j1,j1@LIBC");
__asm__(".globl j1f; .type j1f, @function; j1f: xor %eax,%eax; ret; .size j1f, .-j1f");
__asm__(".symver j1f,j1f@LIBC");
__asm__(".globl jn; .type jn, @function; jn: xor %eax,%eax; ret; .size jn, .-jn");
__asm__(".symver jn,jn@LIBC");
__asm__(".globl jnf; .type jnf, @function; jnf: xor %eax,%eax; ret; .size jnf, .-jnf");
__asm__(".symver jnf,jnf@LIBC");
__asm__(".globl ldexpf; .type ldexpf, @function; ldexpf: xor %eax,%eax; ret; .size ldexpf, .-ldexpf");
__asm__(".symver ldexpf,ldexpf@LIBC");
__asm__(".globl ldexpl; .type ldexpl, @function; ldexpl: xor %eax,%eax; ret; .size ldexpl, .-ldexpl");
__asm__(".symver ldexpl,ldexpl@LIBC");
__asm__(".globl lgamma; .type lgamma, @function; lgamma: xor %eax,%eax; ret; .size lgamma, .-lgamma");
__asm__(".symver lgamma,lgamma@LIBC");
__asm__(".globl lgamma_r; .type lgamma_r, @function; lgamma_r: xor %eax,%eax; ret; .size lgamma_r, .-lgamma_r");
__asm__(".symver lgamma_r,lgamma_r@LIBC");
__asm__(".globl lgammaf; .type lgammaf, @function; lgammaf: xor %eax,%eax; ret; .size lgammaf, .-lgammaf");
__asm__(".symver lgammaf,lgammaf@LIBC");
__asm__(".globl lgammaf_r; .type lgammaf_r, @function; lgammaf_r: xor %eax,%eax; ret; .size lgammaf_r, .-lgammaf_r");
__asm__(".symver lgammaf_r,lgammaf_r@LIBC");
__asm__(".globl lgammal; .type lgammal, @function; lgammal: xor %eax,%eax; ret; .size lgammal, .-lgammal");
__asm__(".symver lgammal,lgammal@LIBC");
__asm__(".globl lgammal_r; .type lgammal_r, @function; lgammal_r: xor %eax,%eax; ret; .size lgammal_r, .-lgammal_r");
__asm__(".symver lgammal_r,lgammal_r@LIBC");
__asm__(".globl llrint; .type llrint, @function; llrint: xor %eax,%eax; ret; .size llrint, .-llrint");
__asm__(".symver llrint,llrint@LIBC");
__asm__(".globl llrintf; .type llrintf, @function; llrintf: xor %eax,%eax; ret; .size llrintf, .-llrintf");
__asm__(".symver llrintf,llrintf@LIBC");
__asm__(".globl llrintl; .type llrintl, @function; llrintl: xor %eax,%eax; ret; .size llrintl, .-llrintl");
__asm__(".symver llrintl,llrintl@LIBC");
__asm__(".globl llround; .type llround, @function; llround: xor %eax,%eax; ret; .size llround, .-llround");
__asm__(".symver llround,llround@LIBC");
__asm__(".globl llroundf; .type llroundf, @function; llroundf: xor %eax,%eax; ret; .size llroundf, .-llroundf");
__asm__(".symver llroundf,llroundf@LIBC");
__asm__(".globl llroundl; .type llroundl, @function; llroundl: xor %eax,%eax; ret; .size llroundl, .-llroundl");
__asm__(".symver llroundl,llroundl@LIBC");
__asm__(".globl log; .type log, @function; log: xor %eax,%eax; ret; .size log, .-log");
__asm__(".symver log,log@LIBC");
__asm__(".globl log10; .type log10, @function; log10: xor %eax,%eax; ret; .size log10, .-log10");
__asm__(".symver log10,log10@LIBC");
__asm__(".globl log10f; .type log10f, @function; log10f: xor %eax,%eax; ret; .size log10f, .-log10f");
__asm__(".symver log10f,log10f@LIBC");
__asm__(".globl log10l; .type log10l, @function; log10l: xor %eax,%eax; ret; .size log10l, .-log10l");
__asm__(".symver log10l,log10l@LIBC");
__asm__(".globl log1p; .type log1p, @function; log1p: xor %eax,%eax; ret; .size log1p, .-log1p");
__asm__(".symver log1p,log1p@LIBC");
__asm__(".globl log1pf; .type log1pf, @function; log1pf: xor %eax,%eax; ret; .size log1pf, .-log1pf");
__asm__(".symver log1pf,log1pf@LIBC");
__asm__(".globl log1pl; .type log1pl, @function; log1pl: xor %eax,%eax; ret; .size log1pl, .-log1pl");
__asm__(".symver log1pl,log1pl@LIBC");
__asm__(".globl log2; .type log2, @function; log2: xor %eax,%eax; ret; .size log2, .-log2");
__asm__(".symver log2,log2@LIBC");
__asm__(".globl log2f; .type log2f, @function; log2f: xor %eax,%eax; ret; .size log2f, .-log2f");
__asm__(".symver log2f,log2f@LIBC");
__asm__(".globl log2l; .type log2l, @function; log2l: xor %eax,%eax; ret; .size log2l, .-log2l");
__asm__(".symver log2l,log2l@LIBC");
__asm__(".globl logb; .type logb, @function; logb: xor %eax,%eax; ret; .size logb, .-logb");
__asm__(".symver logb,logb@LIBC");
__asm__(".globl logbf; .type logbf, @function; logbf: xor %eax,%eax; ret; .size logbf, .-logbf");
__asm__(".symver logbf,logbf@LIBC");
__asm__(".globl logbl; .type logbl, @function; logbl: xor %eax,%eax; ret; .size logbl, .-logbl");
__asm__(".symver logbl,logbl@LIBC");
__asm__(".globl logf; .type logf, @function; logf: xor %eax,%eax; ret; .size logf, .-logf");
__asm__(".symver logf,logf@LIBC");
__asm__(".globl logl; .type logl, @function; logl: xor %eax,%eax; ret; .size logl, .-logl");
__asm__(".symver logl,logl@LIBC");
__asm__(".globl lrint; .type lrint, @function; lrint: xor %eax,%eax; ret; .size lrint, .-lrint");
__asm__(".symver lrint,lrint@LIBC");
__asm__(".globl lrintf; .type lrintf, @function; lrintf: xor %eax,%eax; ret; .size lrintf, .-lrintf");
__asm__(".symver lrintf,lrintf@LIBC");
__asm__(".globl lrintl; .type lrintl, @function; lrintl: xor %eax,%eax; ret; .size lrintl, .-lrintl");
__asm__(".symver lrintl,lrintl@LIBC");
__asm__(".globl lround; .type lround, @function; lround: xor %eax,%eax; ret; .size lround, .-lround");
__asm__(".symver lround,lround@LIBC");
__asm__(".globl lroundf; .type lroundf, @function; lroundf: xor %eax,%eax; ret; .size lroundf, .-lroundf");
__asm__(".symver lroundf,lroundf@LIBC");
__asm__(".globl lroundl; .type lroundl, @function; lroundl: xor %eax,%eax; ret; .size lroundl, .-lroundl");
__asm__(".symver lroundl,lroundl@LIBC");
__asm__(".globl modf; .type modf, @function; modf: xor %eax,%eax; ret; .size modf, .-modf");
__asm__(".symver modf,modf@LIBC");
__asm__(".globl modff; .type modff, @function; modff: xor %eax,%eax; ret; .size modff, .-modff");
__asm__(".symver modff,modff@LIBC");
__asm__(".globl modfl; .type modfl, @function; modfl: xor %eax,%eax; ret; .size modfl, .-modfl");
__asm__(".symver modfl,modfl@LIBC");
__asm__(".globl nan; .type nan, @function; nan: xor %eax,%eax; ret; .size nan, .-nan");
__asm__(".symver nan,nan@LIBC");
__asm__(".globl nanf; .type nanf, @function; nanf: xor %eax,%eax; ret; .size nanf, .-nanf");
__asm__(".symver nanf,nanf@LIBC");
__asm__(".globl nanl; .type nanl, @function; nanl: xor %eax,%eax; ret; .size nanl, .-nanl");
__asm__(".symver nanl,nanl@LIBC");
__asm__(".globl nearbyint; .type nearbyint, @function; nearbyint: xor %eax,%eax; ret; .size nearbyint, .-nearbyint");
__asm__(".symver nearbyint,nearbyint@LIBC");
__asm__(".globl nearbyintf; .type nearbyintf, @function; nearbyintf: xor %eax,%eax; ret; .size nearbyintf, .-nearbyintf");
__asm__(".symver nearbyintf,nearbyintf@LIBC");
__asm__(".globl nearbyintl; .type nearbyintl, @function; nearbyintl: xor %eax,%eax; ret; .size nearbyintl, .-nearbyintl");
__asm__(".symver nearbyintl,nearbyintl@LIBC");
__asm__(".globl nextafter; .type nextafter, @function; nextafter: xor %eax,%eax; ret; .size nextafter, .-nextafter");
__asm__(".symver nextafter,nextafter@LIBC");
__asm__(".globl nextafterf; .type nextafterf, @function; nextafterf: xor %eax,%eax; ret; .size nextafterf, .-nextafterf");
__asm__(".symver nextafterf,nextafterf@LIBC");
__asm__(".globl nextafterl; .type nextafterl, @function; nextafterl: xor %eax,%eax; ret; .size nextafterl, .-nextafterl");
__asm__(".symver nextafterl,nextafterl@LIBC");
__asm__(".globl nexttoward; .type nexttoward, @function; nexttoward: xor %eax,%eax; ret; .size nexttoward, .-nexttoward");
__asm__(".symver nexttoward,nexttoward@LIBC");
__asm__(".globl nexttowardf; .type nexttowardf, @function; nexttowardf: xor %eax,%eax; ret; .size nexttowardf, .-nexttowardf");
__asm__(".symver nexttowardf,nexttowardf@LIBC");
__asm__(".globl nexttowardl; .type nexttowardl, @function; nexttowardl: xor %eax,%eax; ret; .size nexttowardl, .-nexttowardl");
__asm__(".symver nexttowardl,nexttowardl@LIBC");
__asm__(".globl pow; .type pow, @function; pow: xor %eax,%eax; ret; .size pow, .-pow");
__asm__(".symver pow,pow@LIBC");
__asm__(".globl powf; .type powf, @function; powf: xor %eax,%eax; ret; .size powf, .-powf");
__asm__(".symver powf,powf@LIBC");
__asm__(".globl powl; .type powl, @function; powl: xor %eax,%eax; ret; .size powl, .-powl");
__asm__(".symver powl,powl@LIBC");
__asm__(".globl remainder; .type remainder, @function; remainder: xor %eax,%eax; ret; .size remainder, .-remainder");
__asm__(".symver remainder,remainder@LIBC");
__asm__(".globl remainderf; .type remainderf, @function; remainderf: xor %eax,%eax; ret; .size remainderf, .-remainderf");
__asm__(".symver remainderf,remainderf@LIBC");
__asm__(".globl remainderl; .type remainderl, @function; remainderl: xor %eax,%eax; ret; .size remainderl, .-remainderl");
__asm__(".symver remainderl,remainderl@LIBC");
__asm__(".globl remquo; .type remquo, @function; remquo: xor %eax,%eax; ret; .size remquo, .-remquo");
__asm__(".symver remquo,remquo@LIBC");
__asm__(".globl remquof; .type remquof, @function; remquof: xor %eax,%eax; ret; .size remquof, .-remquof");
__asm__(".symver remquof,remquof@LIBC");
__asm__(".globl remquol; .type remquol, @function; remquol: xor %eax,%eax; ret; .size remquol, .-remquol");
__asm__(".symver remquol,remquol@LIBC");
__asm__(".globl rint; .type rint, @function; rint: xor %eax,%eax; ret; .size rint, .-rint");
__asm__(".symver rint,rint@LIBC");
__asm__(".globl rintf; .type rintf, @function; rintf: xor %eax,%eax; ret; .size rintf, .-rintf");
__asm__(".symver rintf,rintf@LIBC");
__asm__(".globl rintl; .type rintl, @function; rintl: xor %eax,%eax; ret; .size rintl, .-rintl");
__asm__(".symver rintl,rintl@LIBC");
__asm__(".globl round; .type round, @function; round: xor %eax,%eax; ret; .size round, .-round");
__asm__(".symver round,round@LIBC");
__asm__(".globl roundf; .type roundf, @function; roundf: xor %eax,%eax; ret; .size roundf, .-roundf");
__asm__(".symver roundf,roundf@LIBC");
__asm__(".globl roundl; .type roundl, @function; roundl: xor %eax,%eax; ret; .size roundl, .-roundl");
__asm__(".symver roundl,roundl@LIBC");
__asm__(".globl scalb; .type scalb, @function; scalb: xor %eax,%eax; ret; .size scalb, .-scalb");
__asm__(".symver scalb,scalb@LIBC");
__asm__(".globl scalbf; .type scalbf, @function; scalbf: xor %eax,%eax; ret; .size scalbf, .-scalbf");
__asm__(".symver scalbf,scalbf@LIBC");
__asm__(".globl scalbln; .type scalbln, @function; scalbln: xor %eax,%eax; ret; .size scalbln, .-scalbln");
__asm__(".symver scalbln,scalbln@LIBC");
__asm__(".globl scalblnf; .type scalblnf, @function; scalblnf: xor %eax,%eax; ret; .size scalblnf, .-scalblnf");
__asm__(".symver scalblnf,scalblnf@LIBC");
__asm__(".globl scalblnl; .type scalblnl, @function; scalblnl: xor %eax,%eax; ret; .size scalblnl, .-scalblnl");
__asm__(".symver scalblnl,scalblnl@LIBC");
__asm__(".globl scalbn; .type scalbn, @function; scalbn: xor %eax,%eax; ret; .size scalbn, .-scalbn");
__asm__(".symver scalbn,scalbn@LIBC");
__asm__(".globl scalbnf; .type scalbnf, @function; scalbnf: xor %eax,%eax; ret; .size scalbnf, .-scalbnf");
__asm__(".symver scalbnf,scalbnf@LIBC");
__asm__(".globl scalbnl; .type scalbnl, @function; scalbnl: xor %eax,%eax; ret; .size scalbnl, .-scalbnl");
__asm__(".symver scalbnl,scalbnl@LIBC");
__asm__(".globl significand; .type significand, @function; significand: xor %eax,%eax; ret; .size significand, .-significand");
__asm__(".symver significand,significand@LIBC");
__asm__(".globl significandf; .type significandf, @function; significandf: xor %eax,%eax; ret; .size significandf, .-significandf");
__asm__(".symver significandf,significandf@LIBC");
__asm__(".globl significandl; .type significandl, @function; significandl: xor %eax,%eax; ret; .size significandl, .-significandl");
__asm__(".symver significandl,significandl@LIBC");
__asm__(".globl sin; .type sin, @function; sin: xor %eax,%eax; ret; .size sin, .-sin");
__asm__(".symver sin,sin@LIBC");
__asm__(".globl sincos; .type sincos, @function; sincos: xor %eax,%eax; ret; .size sincos, .-sincos");
__asm__(".symver sincos,sincos@LIBC");
__asm__(".globl sincosf; .type sincosf, @function; sincosf: xor %eax,%eax; ret; .size sincosf, .-sincosf");
__asm__(".symver sincosf,sincosf@LIBC");
__asm__(".globl sincosl; .type sincosl, @function; sincosl: xor %eax,%eax; ret; .size sincosl, .-sincosl");
__asm__(".symver sincosl,sincosl@LIBC");
__asm__(".globl sinf; .type sinf, @function; sinf: xor %eax,%eax; ret; .size sinf, .-sinf");
__asm__(".symver sinf,sinf@LIBC");
__asm__(".globl sinh; .type sinh, @function; sinh: xor %eax,%eax; ret; .size sinh, .-sinh");
__asm__(".symver sinh,sinh@LIBC");
__asm__(".globl sinhf; .type sinhf, @function; sinhf: xor %eax,%eax; ret; .size sinhf, .-sinhf");
__asm__(".symver sinhf,sinhf@LIBC");
__asm__(".globl sinhl; .type sinhl, @function; sinhl: xor %eax,%eax; ret; .size sinhl, .-sinhl");
__asm__(".symver sinhl,sinhl@LIBC");
__asm__(".globl sinl; .type sinl, @function; sinl: xor %eax,%eax; ret; .size sinl, .-sinl");
__asm__(".symver sinl,sinl@LIBC");
__asm__(".globl sqrt; .type sqrt, @function; sqrt: xor %eax,%eax; ret; .size sqrt, .-sqrt");
__asm__(".symver sqrt,sqrt@LIBC");
__asm__(".globl sqrtf; .type sqrtf, @function; sqrtf: xor %eax,%eax; ret; .size sqrtf, .-sqrtf");
__asm__(".symver sqrtf,sqrtf@LIBC");
__asm__(".globl sqrtl; .type sqrtl, @function; sqrtl: xor %eax,%eax; ret; .size sqrtl, .-sqrtl");
__asm__(".symver sqrtl,sqrtl@LIBC");
__asm__(".globl tan; .type tan, @function; tan: xor %eax,%eax; ret; .size tan, .-tan");
__asm__(".symver tan,tan@LIBC");
__asm__(".globl tanf; .type tanf, @function; tanf: xor %eax,%eax; ret; .size tanf, .-tanf");
__asm__(".symver tanf,tanf@LIBC");
__asm__(".globl tanh; .type tanh, @function; tanh: xor %eax,%eax; ret; .size tanh, .-tanh");
__asm__(".symver tanh,tanh@LIBC");
__asm__(".globl tanhf; .type tanhf, @function; tanhf: xor %eax,%eax; ret; .size tanhf, .-tanhf");
__asm__(".symver tanhf,tanhf@LIBC");
__asm__(".globl tanhl; .type tanhl, @function; tanhl: xor %eax,%eax; ret; .size tanhl, .-tanhl");
__asm__(".symver tanhl,tanhl@LIBC");
__asm__(".globl tanl; .type tanl, @function; tanl: xor %eax,%eax; ret; .size tanl, .-tanl");
__asm__(".symver tanl,tanl@LIBC");
__asm__(".globl tgamma; .type tgamma, @function; tgamma: xor %eax,%eax; ret; .size tgamma, .-tgamma");
__asm__(".symver tgamma,tgamma@LIBC");
__asm__(".globl tgammaf; .type tgammaf, @function; tgammaf: xor %eax,%eax; ret; .size tgammaf, .-tgammaf");
__asm__(".symver tgammaf,tgammaf@LIBC");
__asm__(".globl tgammal; .type tgammal, @function; tgammal: xor %eax,%eax; ret; .size tgammal, .-tgammal");
__asm__(".symver tgammal,tgammal@LIBC");
__asm__(".globl trunc; .type trunc, @function; trunc: xor %eax,%eax; ret; .size trunc, .-trunc");
__asm__(".symver trunc,trunc@LIBC");
__asm__(".globl truncf; .type truncf, @function; truncf: xor %eax,%eax; ret; .size truncf, .-truncf");
__asm__(".symver truncf,truncf@LIBC");
__asm__(".globl truncl; .type truncl, @function; truncl: xor %eax,%eax; ret; .size truncl, .-truncl");
__asm__(".symver truncl,truncl@LIBC");
__asm__(".globl y0; .type y0, @function; y0: xor %eax,%eax; ret; .size y0, .-y0");
__asm__(".symver y0,y0@LIBC");
__asm__(".globl y0f; .type y0f, @function; y0f: xor %eax,%eax; ret; .size y0f, .-y0f");
__asm__(".symver y0f,y0f@LIBC");
__asm__(".globl y1; .type y1, @function; y1: xor %eax,%eax; ret; .size y1, .-y1");
__asm__(".symver y1,y1@LIBC");
__asm__(".globl y1f; .type y1f, @function; y1f: xor %eax,%eax; ret; .size y1f, .-y1f");
__asm__(".symver y1f,y1f@LIBC");
__asm__(".globl yn; .type yn, @function; yn: xor %eax,%eax; ret; .size yn, .-yn");
__asm__(".symver yn,yn@LIBC");
__asm__(".globl ynf; .type ynf, @function; ynf: xor %eax,%eax; ret; .size ynf, .-ynf");
__asm__(".symver ynf,ynf@LIBC");
__asm__(".globl cacoshl; .type cacoshl, @function; cacoshl: xor %eax,%eax; ret; .size cacoshl, .-cacoshl");
__asm__(".symver cacoshl,cacoshl@LIBC_O");
__asm__(".globl cacosl; .type cacosl, @function; cacosl: xor %eax,%eax; ret; .size cacosl, .-cacosl");
__asm__(".symver cacosl,cacosl@LIBC_O");
__asm__(".globl casinhl; .type casinhl, @function; casinhl: xor %eax,%eax; ret; .size casinhl, .-casinhl");
__asm__(".symver casinhl,casinhl@LIBC_O");
__asm__(".globl casinl; .type casinl, @function; casinl: xor %eax,%eax; ret; .size casinl, .-casinl");
__asm__(".symver casinl,casinl@LIBC_O");
__asm__(".globl catanhl; .type catanhl, @function; catanhl: xor %eax,%eax; ret; .size catanhl, .-catanhl");
__asm__(".symver catanhl,catanhl@LIBC_O");
__asm__(".globl catanl; .type catanl, @function; catanl: xor %eax,%eax; ret; .size catanl, .-catanl");
__asm__(".symver catanl,catanl@LIBC_O");
__asm__(".globl ccoshl; .type ccoshl, @function; ccoshl: xor %eax,%eax; ret; .size ccoshl, .-ccoshl");
__asm__(".symver ccoshl,ccoshl@LIBC_O");
__asm__(".globl ccosl; .type ccosl, @function; ccosl: xor %eax,%eax; ret; .size ccosl, .-ccosl");
__asm__(".symver ccosl,ccosl@LIBC_O");
__asm__(".globl cexpl; .type cexpl, @function; cexpl: xor %eax,%eax; ret; .size cexpl, .-cexpl");
__asm__(".symver cexpl,cexpl@LIBC_O");
__asm__(".globl clog; .type clog, @function; clog: xor %eax,%eax; ret; .size clog, .-clog");
__asm__(".symver clog,clog@LIBC_O");
__asm__(".globl clogf; .type clogf, @function; clogf: xor %eax,%eax; ret; .size clogf, .-clogf");
__asm__(".symver clogf,clogf@LIBC_O");
__asm__(".globl clogl; .type clogl, @function; clogl: xor %eax,%eax; ret; .size clogl, .-clogl");
__asm__(".symver clogl,clogl@LIBC_O");
__asm__(".globl cpow; .type cpow, @function; cpow: xor %eax,%eax; ret; .size cpow, .-cpow");
__asm__(".symver cpow,cpow@LIBC_O");
__asm__(".globl cpowf; .type cpowf, @function; cpowf: xor %eax,%eax; ret; .size cpowf, .-cpowf");
__asm__(".symver cpowf,cpowf@LIBC_O");
__asm__(".globl cpowl; .type cpowl, @function; cpowl: xor %eax,%eax; ret; .size cpowl, .-cpowl");
__asm__(".symver cpowl,cpowl@LIBC_O");
__asm__(".globl csinhl; .type csinhl, @function; csinhl: xor %eax,%eax; ret; .size csinhl, .-csinhl");
__asm__(".symver csinhl,csinhl@LIBC_O");
__asm__(".globl csinl; .type csinl, @function; csinl: xor %eax,%eax; ret; .size csinl, .-csinl");
__asm__(".symver csinl,csinl@LIBC_O");
__asm__(".globl ctanhl; .type ctanhl, @function; ctanhl: xor %eax,%eax; ret; .size ctanhl, .-ctanhl");
__asm__(".symver ctanhl,ctanhl@LIBC_O");
__asm__(".globl ctanl; .type ctanl, @function; ctanl: xor %eax,%eax; ret; .size ctanl, .-ctanl");
__asm__(".symver ctanl,ctanl@LIBC_O");
__asm__(".globl __aeabi_d2lz; .type __aeabi_d2lz, @function; __aeabi_d2lz: xor %eax,%eax; ret; .size __aeabi_d2lz, .-__aeabi_d2lz");
__asm__(".symver __aeabi_d2lz,__aeabi_d2lz@LIBC_DEPRECATED");
__asm__(".globl __aeabi_d2ulz; .type __aeabi_d2ulz, @function; __aeabi_d2ulz: xor %eax,%eax; ret; .size __aeabi_d2ulz, .-__aeabi_d2ulz");
__asm__(".symver __aeabi_d2ulz,__aeabi_d2ulz@LIBC_DEPRECATED");
__asm__(".globl __aeabi_f2lz; .type __aeabi_f2lz, @function; __aeabi_f2lz: xor %eax,%eax; ret; .size __aeabi_f2lz, .-__aeabi_f2lz");
__asm__(".symver __aeabi_f2lz,__aeabi_f2lz@LIBC_DEPRECATED");
__asm__(".globl __aeabi_f2ulz; .type __aeabi_f2ulz, @function; __aeabi_f2ulz: xor %eax,%eax; ret; .size __aeabi_f2ulz, .-__aeabi_f2ulz");
__asm__(".symver __aeabi_f2ulz,__aeabi_f2ulz@LIBC_DEPRECATED");
__asm__(".globl __aeabi_l2d; .type __aeabi_l2d, @function; __aeabi_l2d: xor %eax,%eax; ret; .size __aeabi_l2d, .-__aeabi_l2d");
__asm__(".symver __aeabi_l2d,__aeabi_l2d@LIBC_DEPRECATED");
__asm__(".globl __fixdfdi; .type __fixdfdi, @function; __fixdfdi: xor %eax,%eax; ret; .size __fixdfdi, .-__fixdfdi");
__asm__(".symver __fixdfdi,__fixdfdi@LIBC_DEPRECATED");
__asm__(".globl __fixsfdi; .type __fixsfdi, @function; __fixsfdi: xor %eax,%eax; ret; .size __fixsfdi, .-__fixsfdi");
__asm__(".symver __fixsfdi,__fixsfdi@LIBC_DEPRECATED");
__asm__(".globl __fixunsdfdi; .type __fixunsdfdi, @function; __fixunsdfdi: xor %eax,%eax; ret; .size __fixunsdfdi, .-__fixunsdfdi");
__asm__(".symver __fixunsdfdi,__fixunsdfdi@LIBC_DEPRECATED");
__asm__(".globl __fixunssfdi; .type __fixunssfdi, @function; __fixunssfdi: xor %eax,%eax; ret; .size __fixunssfdi, .-__fixunssfdi");
__asm__(".symver __fixunssfdi,__fixunssfdi@LIBC_DEPRECATED");
__asm__(".globl __floatdidf; .type __floatdidf, @function; __floatdidf: xor %eax,%eax; ret; .size __floatdidf, .-__floatdidf");
__asm__(".symver __floatdidf,__floatdidf@LIBC_DEPRECATED");

__asm__(".globl dummy_extra1; .type dummy_extra1, @function; dummy_extra1: xor %eax,%eax; ret; .size dummy_extra1, .-dummy_extra1");
__asm__(".symver dummy_extra1,dummy_extra1@LIBC");
__asm__(".globl dummy_extra2; .type dummy_extra2, @function; dummy_extra2: xor %eax,%eax; ret; .size dummy_extra2, .-dummy_extra2");
__asm__(".symver dummy_extra2,dummy_extra2@LIBC");
