cmake_minimum_required(VERSION 3.14)
project(log-shim LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
add_library(log-shim STATIC include/shims/log_shim.h src/stub.cpp)
target_include_directories(log-shim PUBLIC include/)
target_link_libraries(log-shim PUBLIC utils logger)
set_target_properties(log-shim PROPERTIES CXX_STANDARD 11 CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF)
